# Generated by Django 5.0.6 on 2024-07-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='employment_status',
            field=models.CharField(choices=[('Emp', 'Employee'), ('Entrepreneur', 'Entrepreneur'), ('Unemp', 'Unemployed'), ('Home maker', 'Home maker / House wife')], default='Emp', max_length=12),
        ),
    ]
