# Generated by Django 5.0.6 on 2024-07-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_questionnaire_alumni_meet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='alumni_meet',
            field=models.BooleanField(choices=[('true', 'Yes'), ('false', 'No')], default=False, verbose_name='Would you like to come for Alumni Meet, if the Institute organizes the same'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='college_event_management',
            field=models.BooleanField(choices=[('true', 'Yes'), ('false', 'No')], default=False, verbose_name='Do you like to get involved in our college events management'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='college_outreach_program',
            field=models.BooleanField(choices=[('true', 'Yes'), ('false', 'No')], default=False, verbose_name='Will you be intentional to participate in any of our college social out-reach programs'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='college_promotional_endeavor',
            field=models.BooleanField(choices=[('true', 'Yes'), ('false', 'No')], default=False, verbose_name='Do you have an unforced desirous to contribute your valuable experience and timings for any of the college promotion endeavors'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='guest_college_event',
            field=models.BooleanField(choices=[('true', 'Yes'), ('false', 'No')], default=False, verbose_name='Do you have a wish to present yourself as a guest of our college events'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='job_refer',
            field=models.BooleanField(choices=[('true', 'Yes'), ('false', 'No')], default=False, verbose_name='Are you willing to refer any jobs to your college junior'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='mentor_research_papers',
            field=models.BooleanField(choices=[('true', 'Yes'), ('false', 'No')], default=False, verbose_name='Willful to be a mentor for any research projects to our students'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='placement_cell',
            field=models.BooleanField(choices=[('true', 'Yes'), ('false', 'No')], default=False, verbose_name='Do you like to contribute to KCP placement cell'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='resource_person',
            field=models.BooleanField(choices=[('true', 'Yes'), ('false', 'No')], default=False, verbose_name='Willing to accept our invitation to you to act as a resource person'),
        ),
    ]
